### ISSUE TITLE
End to end tests failing for spurious reasons

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_client_sdk#1015]
### Describe the bug

Presents similar problems to #994 

https://github.com/atsign-foundation/at_client_sdk/actions/runs/4868758186 provides an example where the first run of `end2end_tests` completed with `36 tests passed, 1 failed.` then the second run `end2end_test_14` completed with `36 tests passed, 1 failed.` then third time lucky and the tests pass.

The test that seems to cause the problems is:

```
test/deletion_key_test.dart: A test to verify cached key is deleted in sharedWith secondary when CCD is set to true (failed)
```

### Steps to reproduce

1. First I merge a Dependabot PR that's unrelated to the test surface area
2. Then the full test suite runs
3. And then the end2end tests fail when they shouldn't

### Expected behavior

Tests should pass when merging changes that don't affect the test path

**Comment by gkc** [comment]
@sitaram-kalluri did you mention earlier that you had diagnosed the issue here?

**Comment by gkc** [comment]
Action runs continuing to fail frequently, requiring re-runs

**Comment by purnimavenkatasubbu** [comment]
The tests were failing due to assertions taking place before the sync gets completed. For that, we now added a condition in the sync_initializer to check if localCommitId equals serverCommitId. If syncStatus is a success and localCommitId equals serverCommitId we exit the condition, else we try for 30 seconds.  PR for the changes #1021

**Comment by gkc** [comment]
Thank you @purnimavenkatasubbu
