### ISSUE TITLE
syncProgress.conflictInfo isn't returning the local and remote value

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_client_sdk#1016]
### Describe the bug

When there is a conflicting key in the local and remote secondaries, syncProgress.conflictInfo returns the localValue and remoteValue as null instead of the correct values

### Steps to reproduce

Run the sync_conflict_test.dart
https://github.com/atsign-foundation/at_client_sdk/commit/d2071f54c48d4720876ce3f8bc474a72ee46af7b

### Expected behavior

remoteValue and localValue should be null

### Screenshots

![Screenshot from 2023-05-03 15-14-21](https://user-images.githubusercontent.com/43639593/236123541-5b1fd9a0-87a1-44ae-9683-ff4f49506188.png)

**Comment by sitaram-kalluri** [comment]
Currently (the changes in the trunk branch), the conflictInfo is set if the serverCommitEntry exists in the list of uncommitted entries when pulling the changes from the server to local.

In the process of fixing a bug (Please refer to PR "https://github.com/atsign-foundation/at_client_sdk/pull/1024"), When pulling the changes from the server to the local, if the serverCommitEntry exists in the list of uncommitted entries, then the particular serverCommitEntry is skipped (the entry will not sync to the local secondary), and the lastReceivedServerCommitId is updated.

With the above changes, the control does not go into the section that populates ConflictInfo, because if the serverCommitEntry exists in the uncommitedEntries list, we skip processing the entry.

Following is the approach for the ConflictInfo, refactor the code to populate the conflictInfo and skip syncing the serverCommitEntry to local.

From yesterday's discussion, Since deprecating is not an option, please let me know if the above approach looks good or suggest an alternative.

**Comment by gkc** [comment]
Assume we keep ConflictInfo for its intended purpose which is when there is a conflict that we wish to inform the application about, then it seems to me that yes the code should both (i) populate the conflictInfo and (ii) skip processing the entry (i.e. do not pull it into local storage)

**Comment by sitaram-kalluri** [comment]
The changes are completed. Pending work is PR review
