### ISSUE TITLE
at_client expects internal keys to have namespace (when namespace is not provided through preferences)

### ISSUE THREAD

**Issue by srieteja** [atsign-foundation/at_client_sdk#1075]
### Describe the bug

some atsigns after being activated with activate_cli/onboarding_cli end up in a situation where sync keeps failing due to an exception 
````
SEVERE|2023-06-26 13:34:51.888723|SyncService (@34thundering)|Exception in sync cb049548-7780-4cf0-95c1-7bde8faa1d93. Reason: Failed to syncData caused by namespace is mandatory 
````

When a namespace is not set through at_client preferences, at_client while creating internal keys (e.g. lastReceivedCommitId, lastReceivedNotification) expects a namespace explicitly defined for these keys. And since these keys do not have a specific namespace, the client throws an exception which terminates the client.

### Steps to reproduce

1. First I 'activate a new atsign with activate_cli'
2. Then I 'use that atsign with onboaring_cli'
3. And then 'insert a key into the local secondary'
4. This results in a Sync Failure and the syncs keep failing forever

### Expected behavior

Sync should succeed and not throw any exceptions

### Possible solution

1. exclude internal keys from the namespace scrutiny (possibly in the validatePutRequest() in at_client_impl)
2. use a constant/predefined namespace for all internal keys

### Were you using an atApplication when the bug was found?

AtOnbaordingCli

**Comment by gkc** [comment]
This is a severe bug. Bumping priority to P0

**Comment by srieteja** [comment]
I have seperated this issue into 2 parts:
1) EncryptionPublicKey is causing a sync conflict: reson: this key is being stored on RemoteSecondary and LocalSecondary by onboarding_cli. And with recent changes to sync, there's a mismatch in the commitId for this key. And when this key is being synced from Remote->Local this ends up in a sync conflict.
This is fixed in https://github.com/atsign-foundation/at_libraries/pull/389
2) The second part would be the mention of namespace being mentioned in the exception. This is being currently investigated as to why there is a mention of namespaces even when there are no user created keys.

**Comment by gkc** [comment]
@srieteja can you confirm if this is a current live bug i.e. it's in our published packages? Or it's a bug in an unpublished package - i.e. it's been merged to trunk? Or it's a bug in a branch not yet merged to trunk?

**Comment by srieteja** [comment]
This is not a live bug as of now @gary. This will be an active bug when the at_client dependency will be upgraded to the latest version in onboarding_cli.. As long as it's resolved before our next version publish of at_onboarding_cli, this should not be an issue for anyone.

**Comment by gkc** [comment]
Let me re-ask the question - if I do a dart pub upgrade in a project, thus pulling in latest published version of both packages, will I encounter this bug?

**Comment by srieteja** [comment]
That is possible. Just to be sure, I am verifying that. I will update you in a couple of minutes.
[EDIT] Pulling the latest version of packages is triggering this issue

**Comment by srieteja** [comment]
After some more debugging I found the root cause: Sync service stores a local key 'lastReceivedServerCommitId' and AtClient is excpecting this key to have a namespace; hence the exception message. Making a fix asap

**Comment by VJag** [comment]
Issue description:
--------------------
1. lastReceivedServerCommitId is a local key used in Sync service to persist the last received server commit id.
2. In Srie's test client in the atClintPreferences the namespace has not been set as it is optional
3. However, when the client starts to sync and when the sync service tries to put this key without namespace it is rejected hence the sync fails

ps: Same issue will happen when we start the monitor(lastReceivedNotificationAtKey) or do a put without a namespace
**Note: This bug is not triggered when the namespace is set through AtClientPreference**

Potential solutions:
---------------------
1. Set namespace in atClientPreferences and re-run the client
2. Make namespace mandatory on atClient preferences
3. Make sync service save the key in the user namespace not depending on the namespace from atClientPreferences
(If @ colin is the atSign then the key is saved as lastReceivedServerCommitId.colin) [Preferred]

ps:
For keys that SDK creates for internal use, it would be better to save them in the user namespace. We use the namespace from AtClientPreference as a side effect and the user is free to change it at any time. If the user changes the namespace we lose the state of these internal keys and the sync service and notification service will do things that they are not supposed to do.

Impact:
-------
Only the apps where the default namespace on atClientPreferences is not set will face the issue

**Comment by gkc** [comment]
Thank you for the detailed explanation 👍

**Comment by gkc** [comment]
Dropped priority to P1

**Comment by VJag** [comment]
Srie confirmed that the bug is not triggered when the namespace is set on AtClientPreference

**Comment by gkc** [comment]
Thank you @srieteja and @VJag.

@cconstab @XavierChanth @JeremyTubongbanua This is no longer a blocker for releasing a new version of sshnoports as this bug will not impact the noports programs

**Comment by cconstab** [comment]
But it would it effect people using a regualr atSign with the opensource  noports and other apps ?

We see that with many devs ..

**Comment by gkc** [comment]
@cconstab In general if an app does not set a namespace then weird stuff will happen. @VJag  and I have briefly discussed and we think at a minimum we should set a default value for the namespace, as well as not depending on the namespace for things which do not depend on it. Jagan has some further thoughts which I expect he will bring up on the architecture call.

**Comment by VJag** [comment]
@cconstab @gkc  I will discuss this in arch call today.

**Comment by srieteja** [comment]
Carrying this forward to PR69 for implementation

**Comment by srieteja** [comment]
Implementation and testing have been completed. Pending PR review.
