### ISSUE TITLE
functional test sync_multiple_client_test fails intermittently

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#1369]
### Describe the bug

sync_multiple_client_test functional test fails on first run but passes on re-run
sample failure runs
https://github.com/atsign-foundation/at_client_sdk/actions/runs/10175572645/job/28143281156
https://github.com/atsign-foundation/at_client_sdk/actions/runs/10176267126/attempts/1
https://github.com/atsign-foundation/at_client_sdk/actions/runs/10175572645/attempts/1

### Steps to reproduce

github actions run after PR is raised

### Expected behavior

test should pass on first run

**Comment by gkc** [comment]
another example https://github.com/atsign-foundation/at_client_sdk/actions/runs/10179182431/job/28154382069?pr=1371

**Comment by sitaram-kalluri** [comment]
The issue is fixed in the PR: https://github.com/atsign-foundation/at_server/pull/1938 by @srieteja . That said, the changes are not published and hence the issue still persists. Will publish at_persistence_secondary_server latest version -v.3.0.63 and update the version in at_secondary_server and release the changes to the canary.

**Comment by sitaram-kalluri** [comment]
The changes are released into canary in v3.0.49. Marking this issue as closed.
