### ISSUE TITLE
refactor _get and _put in at_client_impl

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#350]
Lead: @murali-shris (please update if labeled incorrectly)

**Is your feature request related to a problem? Please describe.**
Need to simplify _get() which is currently *very* long with lots of ‘if’ statements, frequently nested

**Describe the solution you'd like**
refactor get and put methods

**Comment by sitaram-kalluri** [comment]
Refactored the get and put method in at_client_impl. Currently the functional test related to notifications are failing because of a minor bug (changes related to support reset of ttb and ttl) in at_persistence_secondary_server. Fixed the issue.
Need to publish the at_persistence_secondary_server for the functional tests to pass.

Require 3 sprint point to bring this task to closure.

**Comment by sitaram-kalluri** [comment]
Publishing packages is in-progress. The progress is tracked using the following git issue: #https://github.com/atsign-foundation/at_client_sdk/issues/381

**Comment by sitaram-kalluri** [comment]
Completed refactoring the get and put method in at_client_impl. Further refactored the encryption_service.dart as well. The get method changes are published. The put method changes are completed and yet to publish will be tracked in [#392](https://github.com/atsign-foundation/at_client_sdk/issues/392)
