### ISSUE TITLE
replace AtClientManager.getInstance()

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#353]
eliminate use of AtClientManager.getInstance() and instead have AtClientImpl, NotificationService, SyncService become aware of each other. An interim step would be to add methods like getNotificationServiceForAtSign(atSign), getSyncServiceForAtSign(atSign), getAtClientForAtSign(atSign)

**Comment by gkc** [comment]
Intent is to remove the static dependency and make it dynamic, primarily for testability and code correctness reasons. For backwards-compatibility, the existing uses of AtClientManager outside of the group of objects it's co-ordinating *must* continue to work as they do now.

**Comment by gkc** [comment]
We are all likely to have different proposals for what to do here. Let's make and discuss those proposals here and once we're agreed then we can implement what we have agreed on.

**Comment by murali-shris** [comment]
Exploring approaches and yet to finalise on the design.

**Comment by gkc** [comment]
Let's clarify the objectives.

1. We're trying to make it possible to test the three collaborators AtClientImpl, NotificationServiceImpl and SyncServiceImpl independently of each other. This means that we can't have any of those implementations refer to their collaborators via *static* AtClientManager.getInstance().getXxx
2. Ideally we would inject the required collaborators into each instance via constructor. However there is at least one circular dependency which means that instead as a first step we will need to provide the 'owning' AtClientManager instance into each collaborator's constructor. Collaborators can then get handles to each other via the atClientManager 'instance' - almost identical to today but via an instance method rather than a static method
3. Backwards compatibility. Existing uses of AtClientManager outside of the group of objects it's co-ordinating *must* continue to work as they do now, with unchanged method signatures (other than perhaps marking some of them deprecated).
4. Minimal intrusion. Let's just do the minimum required to make it possible to test the three collaborators independently without breaking backwards compatibility

**Comment by murali-shris** [comment]
> Let's clarify the objectives.
> 
> 1. We're trying to make it possible to test the three collaborators AtClientImpl, NotificationServiceImpl and SyncServiceImpl independently of each other. This means that we can't have any of those implementations refer to their collaborators via _static_ AtClientManager.getInstance().getXxx
> 2. Ideally we would inject the required collaborators into each instance via constructor. However there is at least one circular dependency which means that instead as a first step we will need to provide the 'owning' AtClientManager instance into each collaborator's constructor. Collaborators can then get handles to each other via that injected atClientManager 'instance' - almost identical to today but via an instance method rather than a static method
> 3. Backwards compatibility. Existing uses of AtClientManager outside of the group of objects it's co-ordinating _must_ continue to work as they do now, with unchanged method signatures (other than perhaps marking some of them deprecated).
> 4. Minimal intrusion. Let's just do the minimum required to make it possible to test the three collaborators independently without breaking backwards compatibility

Thanks for the clarification Gary. I am clear on what exactly needs to be done from here.
