### ISSUE TITLE
client sends null string in batch update command

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#539]
One of the problems reported in the below issue 
https://github.com/atsign-foundation/at_server/issues/709

**Comment by gkc** [comment]
Following detailed investigation, we found that the code path which caused this issue existed in the version of the Catweb app that Colin released in December, but no longer exists now.

This change https://github.com/atsign-foundation/at_server/pull/380/files , which removes this code path by having the HiveKeyStore.get() throw KeyNotFoundException rather than returning null, was merged to trunk on Nov 30 and was in release **_3.0.9_** of at_persistence_secondary_server

Because pubspec.lock is under version control for Catweb, we can see that at the time it was released in December, Catweb's pubspec.lock was using version **_3.0.8_** of at_persistence_secondary_server

How it worked:
1. Client does a put() of a key, with a ttl; it syncs to server
2. Client stops
3. Some time later, server deletes the now-expired key
4. Client starts. Client does a put() of the same key with a new value. Sync starts with this pending put() from the client side, and with a pending delete () from the server side.
5. Updates from server are processed first. Entry for this key is removed from the client's key store
6 Updates from client are processed
6a: client looks up the value for the key
6b: receives null
6c: turns that into the string value 'null', and sends the update to the server

As was shown by Murali's code walk through last week, that sequence is no longer possible because in step 6b, instead of returning null, an exception is now thrown
