### ISSUE TITLE
secure element: at_onboarding_flutter refactoring to use at_chops

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#792]
### Is your feature request related to a problem? Please describe.

See https://github.com/atsign-foundation/at_client_sdk/issues/756

### Describe the solution you'd like

See https://github.com/atsign-foundation/at_client_sdk/issues/756

**Comment by gkc** [comment]
Moving to Backlog as we won't get to it this sprint

**Comment by gkc** [comment]
@murali-shris Has this work been done? I can't remember off the top of my head but I think the necessary work in at_client_mobile was completed, is that right?

**Comment by murali-shris** [comment]
onboarding_service --> onboard uses at_client_service -->onboard which takes care of at_chops instance creation. No additional work is required for this, except upgrading the dependencies in onboarding_flutter package and a round of app testing

**Comment by purnimavenkatasubbu** [comment]
Verified wavi app with the onboarding branch of [at_chops_uptake](https://github.com/atsign-foundation/at_widgets/tree/at_chops_uptake). Everything worked fine. Attaching logs below
[waviLogsOnboarding.txt](https://github.com/atsign-foundation/at_client_sdk/files/10878118/waviLogsOnboarding.txt)


With atmosphere_pro app, I'm getting errors with the third party packages 

Because every version of at_onboarding_flutter from git depends on webview_flutter ^4.0.0 and atsign_atmosphere_pro depends on webview_flutter ^3.0.4,
at_onboarding_flutter from git is forbidden.
So, because atsign_atmosphere_pro depends on at_onboarding_flutter from git, version solving failed.

After I upgrade webview_flutter: ^4.0.0 it throws errors in the app code. Added dependency_overrides for webview_flutter: ^3.0.4

Build fails with the following error

[atMosphereWebview_flutter_logs.txt](https://github.com/atsign-foundation/at_client_sdk/files/10878130/atMosphereWebview_flutter_logs.txt)

**Comment by murali-shris** [comment]
@purnimavenkatasubbu Please create a ticket in atmosphere pro and assign to Sachin

**Comment by murali-shris** [comment]
> @purnimavenkatasubbu Please create a ticket in atmosphere pro and assign to Sachin

https://github.com/atsign-foundation/atmosphere_pro/issues/261

**Comment by murali-shris** [comment]
once atmosphere pro bug is resolved..changes in https://github.com/atsign-foundation/at_widgets/tree/at_chops_uptake can be merged

**Comment by murali-shris** [comment]
> > @purnimavenkatasubbu Please create a ticket in atmosphere pro and assign to Sachin
> 
> [atsign-foundation/atmosphere_pro#261](https://github.com/atsign-foundation/atmosphere_pro/issues/261)

@purnimavenkatasubbu fix has been merged to trunk branch of atmosphere pro. can you please test with at_widgets branch

**Comment by purnimavenkatasubbu** [comment]
Verified atmospherePro app with the changes and published the onboarding package with the fix.
at_onboarding_flutter: ^6.0.3
