### ISSUE TITLE
C++ vs C SDK implementation

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_client_sdk#899]
Discussion Item for Arch Call, we can list the pros and cons here.

**Comment by ksanty** [comment]
@XavierChanth going to add additional context from Qt Group if that's ok.

Players from Qt

1. Roger Mazella, BD
2. Corey Pendleton - Eng Mgmnt
3. Brian Gusso - Sys Eng
4. Sam Davies - Product Eng working on C++ development with us

From Corey:
I’ve collected a few examples which you can run for yourself after you install Qt locally. Note: be sure to check the Qt MQTT module under Additional Libraries for your Qt installation.
Also NOTE: although I’ve got Android, WebAssembly, and MinGW checked below, you only need one set of binaries. Don’t waste time installing those right now. If you’re on Windows, just use the MSVC binaries.

You can review the documentation for our MQTT library here: https://doc.qt.io/qt-6/qtmqtt-examples.html 
And you can run the examples from Qt Creator after installation. To access this from Qt Creator, click the Welcome tab (shown when you first startup) then select Examples and type mqtt in the search box.
You’ll also find a number of potentially related examples by searching for network which may be of interest as well.
 
Qt works to abstract the actual implementations such that it can be re-implemented across different platforms. So if you need sockets or TCP/IP connections, the [Qt Network APIs](https://doc.qt.io/qt-6/qtnetwork-module.html) should be used so that those connections work no matter what OS is in use.
My suggestion would be to take one of those examples and begin modifying it to include the Atsign C++ code within the same project. Once it compiles and can make a connection, we can then extract it into a dynamic library project.

**Comment by xavierchanth** [comment]
https://docs.google.com/document/d/1PJNjjNVJgP61a4SaffxC-nSamE9twEu-VToTBakXzuk/edit

**Comment by xavierchanth** [comment]
See: https://docs.google.com/document/d/1BREmIU-6yQrRqVK1XMZKKWDTpMVAX2JW08uLOw4CzNo/edit
